workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api2.eu1.stackone.com/oas/stackone.json
            - location: https://api2.eu1.stackone.com/oas/hris.json
            - location: https://api2.eu1.stackone.com/oas/ats.json
            - location: https://api2.eu1.stackone.com/oas/crm.json
            - location: https://api2.eu1.stackone.com/oas/marketing.json
            - location: https://api2.eu1.stackone.com/oas/iam.json
targets:
    StackOneRubyClient:
        target: ruby
        source: my-source
        publish:
            rubygems:
                token: $RUBYGEMS_AUTH_TOKEN
        codeSamples:
            output: codeSamples.yaml
