# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  
    # ATS Jobs filters
    class AtsListJobsQueryParamFilter < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # The status of the job
      field :status, T.nilable(::StackOne::Operations::Status), { 'query_param': { 'field_name': 'status' } }
      # Use a string with a date to only select results updated after that given date
      field :updated_after, T.nilable(::String), { 'query_param': { 'field_name': 'updated_after' } }


      sig { params(status: T.nilable(::StackOne::Operations::Status), updated_after: T.nilable(::String)).void }
      def initialize(status: nil, updated_after: nil)
        @status = status
        @updated_after = updated_after
      end
    end
  end
end
