# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    
      # Filter parameters for application changes (supports created_after and change_type)
      class AtsListApplicationChangesQueryParamFilter
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter by the type of change that occurred to the application
        field :change_type, Crystalline::Nilable.new(Models::Operations::ChangeType), { 'query_param': { 'field_name': 'change_type' } }
        # Use a string with a date to only select results created after that given date
        field :created_after, Crystalline::Nilable.new(::DateTime), { 'query_param': { 'field_name': 'created_after' } }

        sig { params(change_type: T.nilable(Models::Operations::ChangeType), created_after: T.nilable(::DateTime)).void }
        def initialize(change_type: nil, created_after: nil)
          @change_type = change_type
          @created_after = created_after
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @change_type == other.change_type
          return false unless @created_after == other.created_after
          true
        end
      end
    end
  end
end
