# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class AtsListBackgroundCheckPackagesResponse
        extend T::Sig
        include Crystalline::MetadataFields
        sig { returns(T.proc.returns(T.nilable(AtsListBackgroundCheckPackagesResponse))) }
        attr_accessor :next_page

        # HTTP response content type for this operation
        field :content_type, ::String

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # The list of background check packages was retrieved.
        field :background_check_package_paginated, Crystalline::Nilable.new(Models::Shared::BackgroundCheckPackagePaginated)

        sig { params(content_type: ::String, headers: T::Hash[Symbol, T::Array[::String]], status_code: ::Integer, raw_response: ::Faraday::Response, background_check_package_paginated: T.nilable(Models::Shared::BackgroundCheckPackagePaginated)).void }
        def initialize(content_type:, headers:, status_code:, raw_response:, background_check_package_paginated: nil)
          @content_type = content_type
          @headers = headers
          @status_code = status_code
          @raw_response = raw_response
          @background_check_package_paginated = background_check_package_paginated
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @headers == other.headers
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @background_check_package_paginated == other.background_check_package_paginated
          true
        end

        def each
          page = self
          loop do
            yield page
            next_page = page.next_page.call if page.next_page
            break if next_page.nil?
            page = T.must(next_page)
          end
        end
      end
    end
  end
end
