# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    
      # ATS Document Filter
      class AtsListApplicationDocumentsQueryParamFilter
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter to select documents by type
        field :type, T.nilable(::String), { 'query_param': { 'field_name': 'type' } }
        # Use a string with a date to only select results updated after that given date
        field :updated_after, T.nilable(::String), { 'query_param': { 'field_name': 'updated_after' } }


        sig { params(type: T.nilable(::String), updated_after: T.nilable(::String)).void }
        def initialize(type: nil, updated_after: nil)
          @type = type
          @updated_after = updated_after
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @updated_after == other.updated_after
          true
        end
      end
    end
  end
end
