# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class AtsCreateInterviewNoteRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :ats_create_notes_request_dto, Models::Shared::AtsCreateNotesRequestDto, { 'request': { 'media_type': 'application/json' } }

        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
        # The account identifier
        field :x_account_id, ::String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }

        sig { params(ats_create_notes_request_dto: Models::Shared::AtsCreateNotesRequestDto, id: ::String, x_account_id: ::String).void }
        def initialize(ats_create_notes_request_dto:, id:, x_account_id:)
          @ats_create_notes_request_dto = ats_create_notes_request_dto
          @id = id
          @x_account_id = x_account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @ats_create_notes_request_dto == other.ats_create_notes_request_dto
          return false unless @id == other.id
          return false unless @x_account_id == other.x_account_id
          true
        end
      end
    end
  end
end
