# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations

      class AtsUpdateApplicationRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :ats_update_application_request_dto, Models::Shared::AtsUpdateApplicationRequestDto, { 'request': { 'media_type': 'application/json' } }

        field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
        # The account identifier
        field :x_account_id, ::String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }
        # Set to "heartbeat" to enable keep-alive newline heartbeats during long-running requests. Response includes Preference-Applied: heartbeat header when honored. (RFC 7240)
        field :prefer, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'Prefer', 'style': 'simple', 'explode': false } }

        sig { params(ats_update_application_request_dto: Models::Shared::AtsUpdateApplicationRequestDto, id: ::String, x_account_id: ::String, prefer: T.nilable(::String)).void }
        def initialize(ats_update_application_request_dto:, id:, x_account_id:, prefer: nil)
          @ats_update_application_request_dto = ats_update_application_request_dto
          @id = id
          @x_account_id = x_account_id
          @prefer = prefer
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @ats_update_application_request_dto == other.ats_update_application_request_dto
          return false unless @id == other.id
          return false unless @x_account_id == other.x_account_id
          return false unless @prefer == other.prefer
          true
        end
      end
    end
  end
end
