# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class AtsGetLocationResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # The location with the given identifier was retrieved.
        field :ats_location_result, Crystalline::Nilable.new(Models::Shared::ATSLocationResult)

        sig { params(content_type: ::String, headers: T::Hash[Symbol, T::Array[::String]], status_code: ::Integer, raw_response: ::Faraday::Response, ats_location_result: T.nilable(Models::Shared::ATSLocationResult)).void }
        def initialize(content_type:, headers:, status_code:, raw_response:, ats_location_result: nil)
          @content_type = content_type
          @headers = headers
          @status_code = status_code
          @raw_response = raw_response
          @ats_location_result = ats_location_result
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @headers == other.headers
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @ats_location_result == other.ats_location_result
          true
        end
      end
    end
  end
end
