# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  

    class CreateRequest < ::StackOne::Utils::FieldAugmented
      extend T::Sig


      field :id, ::Float, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

      field :request_body, T::Array[::StackOne::Shared::CreateEvent], { 'request': { 'media_type': 'application/json' } }
      # The account identifier
      field :x_account_id, ::String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }


      sig { params(id: ::Float, request_body: T::Array[::StackOne::Shared::CreateEvent], x_account_id: ::String).void }
      def initialize(id: nil, request_body: nil, x_account_id: nil)
        @id = id
        @request_body = request_body
        @x_account_id = x_account_id
      end
    end
  end
end
