# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
      # Present on protocol-level failure. Tool-level failures use result with isError: true instead.
      class Error
        extend T::Sig
        include Crystalline::MetadataFields


        field :code, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('code') } }

        field :message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('message') } }
        # Additional error context
        field :data, Crystalline::Nilable.new(::Object), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('data') } }

        sig { params(code: T.nilable(::Float), message: T.nilable(::String), data: T.nilable(::Object)).void }
        def initialize(code: nil, message: nil, data: nil)
          @code = code
          @message = message
          @data = data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @code == other.code
          return false unless @message == other.message
          return false unless @data == other.data
          true
        end
      end
    end
  end
end
