# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    
      # HrisListShiftsQueryParamStatus - Filter to select shifts by status
      class HrisListShiftsQueryParamStatus < T::Enum


        enums do
          DRAFT = new('draft')
          PUBLISHED = new('published')
          CONFIRMED = new('confirmed')
          CANCELLED = new('cancelled')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
