# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class Include < T::Enum


        enums do
          OPERATION_DETAILS = new('operation_details')
        end
      end
    end
  end
end
