# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class LmsCreateCollectionRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :lms_create_collection_request_dto, Models::Shared::LmsCreateCollectionRequestDto, { 'request': { 'media_type': 'application/json' } }
        # The account identifier
        field :x_account_id, ::String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }


        sig { params(lms_create_collection_request_dto: Models::Shared::LmsCreateCollectionRequestDto, x_account_id: ::String).void }
        def initialize(lms_create_collection_request_dto: nil, x_account_id: nil)
          @lms_create_collection_request_dto = lms_create_collection_request_dto
          @x_account_id = x_account_id
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @lms_create_collection_request_dto == other.lms_create_collection_request_dto
          return false unless @x_account_id == other.x_account_id
          true
        end
      end
    end
  end
end
