# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class MessagingSendMessageRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :messaging_message_send_request_dto, Models::Shared::MessagingMessageSendRequestDto, { 'request': { 'media_type': 'application/json' } }
        # The account identifier
        field :x_account_id, ::String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }

        sig { params(messaging_message_send_request_dto: Models::Shared::MessagingMessageSendRequestDto, x_account_id: ::String).void }
        def initialize(messaging_message_send_request_dto:, x_account_id:)
          @messaging_message_send_request_dto = messaging_message_send_request_dto
          @x_account_id = x_account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @messaging_message_send_request_dto == other.messaging_message_send_request_dto
          return false unless @x_account_id == other.x_account_id
          true
        end
      end
    end
  end
end
