# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
      # ParamStyle - Parameter schema style: "nested" (default) groups by location, "flat_prefixed" flattens with location prefix, "flat_smart" flattens and only prefixes on name collision
      class ParamStyle < T::Enum
        enums do
          NESTED = new('nested')
          FLAT_PREFIXED = new('flat_prefixed')
          FLAT_SMART = new('flat_smart')
        end
      end
    end
  end
end
