# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    
      # QueryParamOrderBy - The field to order the results by.
      class QueryParamOrderBy < T::Enum
        enums do
          PROVIDER = new('provider')
          SERVICE = new('service')
          STATUS = new('status')
          EVENT_DATETIME = new('eventDatetime')
          DURATION = new('duration')
        end
      end
    end
  end
end
