# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  

    class StackoneListStepLogsRequest < ::Crystalline::FieldAugmented
      extend T::Sig

      # Filter parameters that allow greater customisation of the list response
      field :filter, T.nilable(::StackOne::Operations::QueryParamFilter), { 'query_param': { 'field_name': 'filter', 'style': 'form', 'explode': true } }
      # The include parameter allows you to include additional data in the response.
      field :include, T.nilable(::StackOne::Operations::StackoneListStepLogsQueryParamInclude), { 'query_param': { 'field_name': 'include', 'style': 'form', 'explode': true } }
      # The unified cursor
      field :next_, T.nilable(::String), { 'query_param': { 'field_name': 'next', 'style': 'form', 'explode': true } }
      # The field to order the results by.
      field :order_by, T.nilable(::StackOne::Operations::StackoneListStepLogsQueryParamOrderBy), { 'query_param': { 'field_name': 'order_by', 'style': 'form', 'explode': true } }
      # The direction to order the results by.
      field :order_direction, T.nilable(::StackOne::Operations::StackoneListStepLogsQueryParamOrderDirection), { 'query_param': { 'field_name': 'order_direction', 'style': 'form', 'explode': true } }
      # The number of results per page (default value is 25)
      field :page_size, T.nilable(::Float), { 'query_param': { 'field_name': 'page_size', 'style': 'form', 'explode': true } }


      sig { params(filter: T.nilable(::StackOne::Operations::QueryParamFilter), include: T.nilable(::StackOne::Operations::StackoneListStepLogsQueryParamInclude), next_: T.nilable(::String), order_by: T.nilable(::StackOne::Operations::StackoneListStepLogsQueryParamOrderBy), order_direction: T.nilable(::StackOne::Operations::StackoneListStepLogsQueryParamOrderDirection), page_size: T.nilable(::Float)).void }
      def initialize(filter: nil, include: nil, next_: nil, order_by: nil, order_direction: nil, page_size: nil)
        @filter = filter
        @include = include
        @next_ = next_
        @order_by = order_by
        @order_direction = order_direction
        @page_size = page_size
      end
    end
  end
end
