# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations
    

      class StackoneListPlatformLogsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter parameters that allow greater customisation of the list response
        field :filter, Crystalline::Nilable.new(Models::Operations::QueryParamFilter), { 'query_param': { 'field_name': 'filter', 'style': 'form', 'explode': true } }
        # The unified cursor
        field :next_, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'next', 'style': 'form', 'explode': true } }
        # The field to order the results by.
        field :order_by, Crystalline::Nilable.new(Models::Operations::StackoneListPlatformLogsQueryParamOrderBy), { 'query_param': { 'field_name': 'order_by', 'style': 'form', 'explode': true } }
        # The direction to order the results by.
        field :order_direction, Crystalline::Nilable.new(Models::Operations::StackoneListPlatformLogsQueryParamOrderDirection), { 'query_param': { 'field_name': 'order_direction', 'style': 'form', 'explode': true } }
        # The number of results per page (default value is 25)
        field :page_size, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'page_size', 'style': 'form', 'explode': true } }

        sig { params(filter: T.nilable(Models::Operations::QueryParamFilter), next_: T.nilable(::String), order_by: T.nilable(Models::Operations::StackoneListPlatformLogsQueryParamOrderBy), order_direction: T.nilable(Models::Operations::StackoneListPlatformLogsQueryParamOrderDirection), page_size: T.nilable(::Float)).void }
        def initialize(filter: nil, next_: nil, order_by: nil, order_direction: nil, page_size: nil)
          @filter = filter
          @next_ = next_
          @order_by = order_by
          @order_direction = order_direction
          @page_size = page_size
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @filter == other.filter
          return false unless @next_ == other.next_
          return false unless @order_by == other.order_by
          return false unless @order_direction == other.order_direction
          return false unless @page_size == other.page_size
          true
        end
      end
    end
  end
end
