# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations

      class StackoneListAuthConfigsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter auth configs by connector key
        field :connector_key, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'connector_key', 'style': 'form', 'explode': true } }
        # Filter auth configs by their enabled state
        field :enabled, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'query_param': { 'field_name': 'enabled', 'style': 'form', 'explode': true } }
        # The page number of the results to fetch
        field :page, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # The number of results per page
        field :page_size, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'page_size', 'style': 'form', 'explode': true } }

        sig { params(connector_key: T.nilable(::String), enabled: T.nilable(T::Boolean), page: T.nilable(::Float), page_size: T.nilable(::Float)).void }
        def initialize(connector_key: nil, enabled: nil, page: nil, page_size: 25.0)
          @connector_key = connector_key
          @enabled = enabled
          @page = page
          @page_size = page_size
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @connector_key == other.connector_key
          return false unless @enabled == other.enabled
          return false unless @page == other.page
          return false unless @page_size == other.page_size
          true
        end
      end
    end
  end
end
