# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Operations

      class StackoneListConnectorProfilesResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # The list of connector profiles was retrieved.
        field :connector_profiles_paginated, Crystalline::Nilable.new(Models::Shared::ConnectorProfilesPaginated)

        sig { params(content_type: ::String, headers: T::Hash[Symbol, T::Array[::String]], status_code: ::Integer, raw_response: ::Faraday::Response, connector_profiles_paginated: T.nilable(Models::Shared::ConnectorProfilesPaginated)).void }
        def initialize(content_type:, headers:, status_code:, raw_response:, connector_profiles_paginated: nil)
          @content_type = content_type
          @headers = headers
          @status_code = status_code
          @raw_response = raw_response
          @connector_profiles_paginated = connector_profiles_paginated
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @headers == other.headers
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @connector_profiles_paginated == other.connector_profiles_paginated
          true
        end
      end
    end
  end
end
