name: Publish

"on":
  push:
    paths:
      - 'RELEASES.md'
    branches:
      - main

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14
    with:
      publish_ruby: true
      create_release: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      rubygems_auth_token: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
