name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 9 * * 1
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v14
    with:
      force: ${{ github.event.inputs.force }}
      languages: |
        - ruby
      mode: pr
      openapi_docs: |
        - https://api2.eu1.stackone.com/oas/stackone.json
        - https://api2.eu1.stackone.com/oas/hris.json
      publish_ruby: true
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      rubygems_auth_token: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
