# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class ActionsSyncedSyncChoice
        extend T::Sig
        include Crystalline::MetadataFields

        # Pass this as `sync_id` to select this sync.
        field :sync_id, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('sync_id'), required: true } }
        # Disambiguated label: the name, with parameters appended when the name alone does not distinguish this choice from another.
        field :sync_label, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('sync_label'), required: true } }
        # The sync's raw name. Not unique, and may be the bare action id.
        field :sync_name, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('sync_name'), required: true } }

        sig { params(sync_id: ::String, sync_label: ::String, sync_name: ::String).void }
        def initialize(sync_id:, sync_label:, sync_name:)
          @sync_id = sync_id
          @sync_label = sync_label
          @sync_name = sync_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @sync_id == other.sync_id
          return false unless @sync_label == other.sync_label
          return false unless @sync_name == other.sync_name
          true
        end
      end
    end
  end
end
