# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class ActionsSyncedResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Metadata about the datasync operation
        field :datasync, Models::Shared::ActionsSyncedDatasync, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('datasync'), required: true } }
        # Present instead of `data` when the request set `aggs`: the OpenSearch aggregation results, keyed the same as the requested `aggs`.
        field :aggregations, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('aggregations') } }
        # The synced records for the requested action
        field :data, Crystalline::Nilable.new(Crystalline::Array.new(Crystalline::Hash.new(Symbol, ::Object))), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('data') } }

        sig { params(datasync: Models::Shared::ActionsSyncedDatasync, aggregations: T.nilable(T::Hash[Symbol, ::Object]), data: T.nilable(T::Array[T::Hash[Symbol, ::Object]])).void }
        def initialize(datasync:, aggregations: nil, data: nil)
          @datasync = datasync
          @aggregations = aggregations
          @data = data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @datasync == other.datasync
          return false unless @aggregations == other.aggregations
          return false unless @data == other.data
          true
        end
      end
    end
  end
end
