# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class ActionsRpcRequestDto
        extend T::Sig
        include Crystalline::MetadataFields

        # The action to execute
        field :action, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('action'), required: true } }
        # Request body for the action
        field :body, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('body') } }
        # Headers for the action
        field :headers, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('headers') } }
        # Path parameters for the action
        field :path, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('path') } }
        # Query parameters for the action
        field :query, Crystalline::Nilable.new(Models::Shared::Query), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('query') } }

        sig { params(action: ::String, body: T.nilable(T::Hash[Symbol, ::Object]), headers: T.nilable(T::Hash[Symbol, ::Object]), path: T.nilable(T::Hash[Symbol, ::Object]), query: T.nilable(Models::Shared::Query)).void }
        def initialize(action:, body: nil, headers: nil, path: nil, query: nil)
          @action = action
          @body = body
          @headers = headers
          @path = path
          @query = query
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @action == other.action
          return false unless @body == other.body
          return false unless @headers == other.headers
          return false unless @path == other.path
          return false unless @query == other.query
          true
        end
      end
    end
  end
end
