# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class ActionMetaItem
        extend T::Sig
        include Crystalline::MetadataFields

        # The action details for the action
        field :action_details, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('action_details') } }
        # The authentication methods supported by this action
        field :authentication, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::AuthenticationMetaItem)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('authentication') } }
        # The action description
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('description') } }
        # Whether this action requires parameters to be supplied when it is synced. Such actions cannot be linked automatically for every account — each schedule must be created with its parameter values.
        field :has_required_parameters, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('has_required_parameters') } }
        # The action ID
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }
        # The action label
        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('label') } }
        # The required scopes for the action
        field :required_scopes, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('required_scopes') } }
        # The schema type for the action
        field :schema_type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('schema_type') } }
        # Whether this action supports incremental syncs (has an incremental strategy).
        field :supports_incremental, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('supports_incremental') } }
        # Whether this action can be synced with the datasync v2 sync engine.
        field :syncable, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('syncable') } }
        # The tags associated with this action
        field :tags, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('tags') } }

        sig { params(action_details: T.nilable(T::Hash[Symbol, ::Object]), authentication: T.nilable(T::Array[Models::Shared::AuthenticationMetaItem]), description: T.nilable(::String), has_required_parameters: T.nilable(T::Boolean), id: T.nilable(::String), label: T.nilable(::String), required_scopes: T.nilable(T::Array[::String]), schema_type: T.nilable(::String), supports_incremental: T.nilable(T::Boolean), syncable: T.nilable(T::Boolean), tags: T.nilable(T::Array[::String])).void }
        def initialize(action_details: nil, authentication: nil, description: nil, has_required_parameters: nil, id: nil, label: nil, required_scopes: nil, schema_type: nil, supports_incremental: nil, syncable: nil, tags: nil)
          @action_details = action_details
          @authentication = authentication
          @description = description
          @has_required_parameters = has_required_parameters
          @id = id
          @label = label
          @required_scopes = required_scopes
          @schema_type = schema_type
          @supports_incremental = supports_incremental
          @syncable = syncable
          @tags = tags
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @action_details == other.action_details
          return false unless @authentication == other.authentication
          return false unless @description == other.description
          return false unless @has_required_parameters == other.has_required_parameters
          return false unless @id == other.id
          return false unless @label == other.label
          return false unless @required_scopes == other.required_scopes
          return false unless @schema_type == other.schema_type
          return false unless @supports_incremental == other.supports_incremental
          return false unless @syncable == other.syncable
          return false unless @tags == other.tags
          true
        end
      end
    end
  end
end
