# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # AggregationPostDtoOrderBy - The field to order the results by
      class AggregationPostDtoOrderBy
        include ::Crystalline::Enum
        enums do
          START_TIME = new('start_time')
          END_TIME = new('end_time')
          EVENT_TIME = new('event_time')
          DURATION_MS = new('duration_ms')
        end
        open!
      end
    end
  end
end
