# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class AggregationPostDtoLogType < T::Enum
        enums do
          ACTION = new('action')
          UNIFIED = new('unified')
        end
      end
    end
  end
end
