# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # AssignmentSchemasValue - The StackOne unified result status.
      class AssignmentSchemasValue
        include ::Crystalline::Enum
        enums do
          PASS = new('Pass')
          FAIL = new('Fail')
          UNMAPPED_VALUE = new('unmapped_value')
        end
        open!
      end
    end
  end
end
