# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # AtsUpdateNotesRequestDtoValue - The visibility of the notes.
      class AtsUpdateNotesRequestDtoValue
        include ::Crystalline::Enum
        enums do
          PRIVATE = new('private')
          PUBLIC = new('public')
          UNMAPPED_VALUE = new('unmapped_value')
        end
        open!
      end
    end
  end
end
