# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # AttachmentValue - The content type of the attachment.
      class AttachmentValue < T::Enum


        enums do
          TEXT = new('text')
          PDF = new('pdf')
          VIDEO = new('video')
          OTHER = new('other')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
