# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class BackgroundCheckOrderJob < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # Hiring team for the job.
      field :hiring_team, T.nilable(T::Array[::StackOne::Shared::AssessmentsRequestsJobHiringTeamApiModel]), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('hiring_team') } }
      # Unique identifier
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }
      # Value to pass through to the provider
      field :passthrough, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('passthrough') } }
      # Title of the job
      field :title, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('title') } }


      sig { params(hiring_team: T.nilable(T::Array[::StackOne::Shared::AssessmentsRequestsJobHiringTeamApiModel]), id: T.nilable(::String), passthrough: T.nilable(T::Hash[Symbol, ::Object]), title: T.nilable(::String)).void }
      def initialize(hiring_team: nil, id: nil, passthrough: nil, title: nil)
        @hiring_team = hiring_team
        @id = id
        @passthrough = passthrough
        @title = title
      end
    end
  end
end
