# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class Category
        extend T::Sig
        include Crystalline::MetadataFields

        # Whether the category is active and therefore available for use
        field :active, Crystalline::Nilable.new(Crystalline::Union.new(Crystalline::Boolean.new, Models::Shared::Category2)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('active') } }
        # The hierarchal level of the category
        field :hierarchy, Crystalline::Nilable.new(Models::Shared::Hierarchy), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('hierarchy') } }
        # The ID associated with this category
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }
        # The language associated with this category
        field :language, Crystalline::Nilable.new(Models::Shared::Language), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('language') } }
        # The hierarchal level of the category
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :level, Crystalline::Nilable.new(Models::Shared::Level), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('level') } }
        # The name associated with this category
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('name') } }
        # Provider's unique identifier
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('remote_id') } }
        # Custom Unified Fields configured in your StackOne project
        field :unified_custom_fields, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('unified_custom_fields') } }

        sig { params(active: T.nilable(T.any(T::Boolean, Models::Shared::Category2)), hierarchy: T.nilable(Models::Shared::Hierarchy), id: T.nilable(::String), language: T.nilable(Models::Shared::Language), level: T.nilable(Models::Shared::Level), name: T.nilable(::String), remote_id: T.nilable(::String), unified_custom_fields: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(active: nil, hierarchy: nil, id: nil, language: nil, level: nil, name: nil, remote_id: nil, unified_custom_fields: nil)
          @active = active
          @hierarchy = hierarchy
          @id = id
          @language = language
          @level = level
          @name = name
          @remote_id = remote_id
          @unified_custom_fields = unified_custom_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @active == other.active
          return false unless @hierarchy == other.hierarchy
          return false unless @id == other.id
          return false unless @language == other.language
          return false unless @level == other.level
          return false unless @name == other.name
          return false unless @remote_id == other.remote_id
          return false unless @unified_custom_fields == other.unified_custom_fields
          true
        end
      end
    end
  end
end
