# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class CheckPermissionsResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Permission check result data
        field :data, Crystalline::Nilable.new(Models::Shared::CheckPermissionsResponseData), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('data') } }

        sig { params(data: T.nilable(Models::Shared::CheckPermissionsResponseData)).void }
        def initialize(data: nil)
          @data = data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          true
        end
      end
    end
  end
end
