# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class CompletionValue < T::Enum
        enums do
          CONTENT = new('content')
          COURSE = new('course')
          COLLECTION = new('collection')
        end
      end
    end
  end
end
