# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # The connector display data — name, logo and categories. Only present when requested via `?expand=connector`; `connector_key`, `connector_version` and `connector_owner` are always returned regardless.
      class Connector
        extend T::Sig
        include Crystalline::MetadataFields

        # The connector categories
        field :categories, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('categories'), required: true } }
        # The connector key
        field :key, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('key'), required: true } }
        # The connector logo. Falls back to a placeholder when none is declared.
        field :logo_url, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('logo_url'), required: true } }
        # The connector owner. Defaults to the global `stackone` owner.
        field :owner, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('owner'), required: true } }
        # The connector display name. `null` when the connector is unknown.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('name'), required: true } }
        # The connector version the log was served by
        field :version, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('version'), required: true } }

        sig { params(categories: T::Array[::String], key: ::String, logo_url: ::String, owner: ::String, name: T.nilable(::String), version: T.nilable(::String)).void }
        def initialize(categories:, key:, logo_url:, owner:, name: nil, version: nil)
          @categories = categories
          @key = key
          @logo_url = logo_url
          @owner = owner
          @name = name
          @version = version
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @categories == other.categories
          return false unless @key == other.key
          return false unless @logo_url == other.logo_url
          return false unless @owner == other.owner
          return false unless @name == other.name
          return false unless @version == other.version
          true
        end
      end
    end
  end
end
