# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # ConnectSessionCreateType - The connect session account type
      class ConnectSessionCreateType
        include ::Crystalline::Enum
        enums do
          PRODUCTION = new('production')
          TEST = new('test')
        end
        open!
      end
    end
  end
end
