# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class ConnectSession
        extend T::Sig
        include Crystalline::MetadataFields


        field :created_at, ::DateTime, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('created_at'), required: true, 'decoder': ::StackOne::Utils.datetime_from_iso_format(false) } }

        field :id, ::Float, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id'), required: true } }

        field :organization_id, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('organization_id'), required: true } }

        field :origin_owner_id, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('origin_owner_id'), required: true } }

        field :origin_owner_name, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('origin_owner_name'), required: true } }

        field :project_id, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('project_id'), required: true } }

        field :account_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('account_id') } }

        field :categories, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::Categories)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('categories') } }
        # The connector profile ID associated with this connect session
        field :connector_profile_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('connector_profile_id') } }
        # External trigger token to be used to trigger actions on the account
        field :external_trigger_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('external_trigger_token') } }
        # Deprecated: use `connector_profile_id` instead. The integration ID (UUID) associated with this connect session.
        #
        # @deprecated true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :integration_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('integration_id') } }

        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('label') } }
        # The most recent connection attempt initiated against this session, if any. Use this to poll for OAuth completion: when status is "authenticated", the resulting account is at account_secure_id.
        field :latest_connection_attempt, Crystalline::Nilable.new(Models::Shared::LatestConnectionAttempt), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('latest_connection_attempt') } }
        # Arbitrary set of key and values defined during the session token creation. This can be used to tag an account (eg. based on their pricing plan)
        field :metadata, Crystalline::Nilable.new(Models::Shared::Metadata), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('metadata') } }

        field :origin_username, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('origin_username') } }

        field :provider, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('provider') } }
        # The connect session account type
        field :type, Crystalline::Nilable.new(Models::Shared::ConnectSessionType), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('type'), 'decoder': ::StackOne::Utils.open_enum_from_string(Models::Shared::ConnectSessionType, true) } }

        sig { params(created_at: ::DateTime, id: ::Float, organization_id: ::String, origin_owner_id: ::String, origin_owner_name: ::String, project_id: ::String, account_id: T.nilable(::String), categories: T.nilable(T::Array[Models::Shared::Categories]), connector_profile_id: T.nilable(::String), external_trigger_token: T.nilable(::String), integration_id: T.nilable(::String), label: T.nilable(::String), latest_connection_attempt: T.nilable(Models::Shared::LatestConnectionAttempt), metadata: T.nilable(Models::Shared::Metadata), origin_username: T.nilable(::String), provider: T.nilable(::String), type: T.nilable(Models::Shared::ConnectSessionType)).void }
        def initialize(created_at:, id:, organization_id:, origin_owner_id:, origin_owner_name:, project_id:, account_id: nil, categories: nil, connector_profile_id: nil, external_trigger_token: nil, integration_id: nil, label: nil, latest_connection_attempt: nil, metadata: nil, origin_username: nil, provider: nil, type: nil)
          @created_at = created_at
          @id = id
          @organization_id = organization_id
          @origin_owner_id = origin_owner_id
          @origin_owner_name = origin_owner_name
          @project_id = project_id
          @account_id = account_id
          @categories = categories
          @connector_profile_id = connector_profile_id
          @external_trigger_token = external_trigger_token
          @integration_id = integration_id
          @label = label
          @latest_connection_attempt = latest_connection_attempt
          @metadata = metadata
          @origin_username = origin_username
          @provider = provider
          @type = type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @created_at == other.created_at
          return false unless @id == other.id
          return false unless @organization_id == other.organization_id
          return false unless @origin_owner_id == other.origin_owner_id
          return false unless @origin_owner_name == other.origin_owner_name
          return false unless @project_id == other.project_id
          return false unless @account_id == other.account_id
          return false unless @categories == other.categories
          return false unless @connector_profile_id == other.connector_profile_id
          return false unless @external_trigger_token == other.external_trigger_token
          return false unless @integration_id == other.integration_id
          return false unless @label == other.label
          return false unless @latest_connection_attempt == other.latest_connection_attempt
          return false unless @metadata == other.metadata
          return false unless @origin_username == other.origin_username
          return false unless @provider == other.provider
          return false unless @type == other.type
          true
        end
      end
    end
  end
end
