# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class ConnectorProfileVersion
        extend T::Sig
        include Crystalline::MetadataFields

        # Whether this version is a built-in StackOne connector (true) or a custom one (false)
        field :builtin, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('builtin'), required: true } }
        # The owner of this connector version. "stackone" for built-in connectors.
        field :owner, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('owner'), required: true } }
        # Whether this version is the one currently pinned for the connector profile
        field :pinned, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('pinned'), required: true } }
        # The connector version
        field :version, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('version'), required: true } }

        sig { params(builtin: T::Boolean, owner: ::String, pinned: T::Boolean, version: ::String).void }
        def initialize(builtin:, owner:, pinned:, version:)
          @builtin = builtin
          @owner = owner
          @pinned = pinned
          @version = version
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @builtin == other.builtin
          return false unless @owner == other.owner
          return false unless @pinned == other.pinned
          return false unless @version == other.version
          true
        end
      end
    end
  end
end
