# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # Stackone enum identifying the status of content block.
      class ContentBlockStatus
        extend T::Sig
        include Crystalline::MetadataFields

        # The source value of the status.
        field :source_value, Crystalline::Nilable.new(Crystalline::Union.new(::String, ::Float, Crystalline::Boolean.new, Models::Shared::ContentBlock4, Crystalline::Array.new(::Object))), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('source_value') } }
        # The Status of the content blocks.
        field :value, Crystalline::Nilable.new(Models::Shared::ContentBlockValue), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('value'), 'decoder': Utils.enum_from_string(Models::Shared::ContentBlockValue, true) } }

        sig { params(source_value: T.nilable(T.any(::String, ::Float, T::Boolean, Models::Shared::ContentBlock4, T::Array[::Object])), value: T.nilable(Models::Shared::ContentBlockValue)).void }
        def initialize(source_value: nil, value: nil)
          @source_value = source_value
          @value = value
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @source_value == other.source_value
          return false unless @value == other.value
          true
        end
      end
    end
  end
end
