# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class ContentType
        extend T::Sig
        include Crystalline::MetadataFields

        # The source value of the content type.
        field :source_value, Crystalline::Nilable.new(Crystalline::Union.new(::String, ::Float, Crystalline::Boolean.new, Models::Shared::ApplicationAttachment4, Crystalline::Array.new(::Object))), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('source_value') } }
        # The content type of the attachment.
        field :value, Crystalline::Nilable.new(Models::Shared::ApplicationAttachmentValue), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('value'), 'decoder': Utils.enum_from_string(Models::Shared::ApplicationAttachmentValue, true) } }

        sig { params(source_value: T.nilable(T.any(::String, ::Float, T::Boolean, Models::Shared::ApplicationAttachment4, T::Array[::Object])), value: T.nilable(Models::Shared::ApplicationAttachmentValue)).void }
        def initialize(source_value: nil, value: nil)
          @source_value = source_value
          @value = value
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @source_value == other.source_value
          return false unless @value == other.value
          true
        end
      end
    end
  end
end
