# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class Dimensions < T::Enum
        enums do
          CONNECTOR_KEY = new('connector_key')
          SUCCESS = new('success')
          ACTION_TYPE = new('action_type')
          MODE = new('mode')
          SERVICE = new('service')
          RESOURCE = new('resource')
          ACTION_ID = new('action_id')
          HTTP_METHOD = new('http_method')
          ACCOUNT_SECURE_ID = new('account_secure_id')
          SOURCE_TYPE = new('source_type')
          STATUS_CODE = new('status_code')
          ORIGIN_OWNER_ID = new('origin_owner_id')
          SOURCE_ID = new('source_id')
          IS_BACKGROUND = new('is_background')
        end
      end
    end
  end
end
