# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class EntitySkills < ::Crystalline::FieldAugmented
      extend T::Sig

      # Whether the skill is active and therefore available for use
      field :active, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('active') } }
      # The ID associated with this skill
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }
      # The language associated with this skill
      field :language, T.nilable(::StackOne::Shared::EntitySkillsLanguage), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('language') } }
      # The proficiency level of the skill
      field :maximum_proficiency, T.nilable(::StackOne::Shared::MaximumProficiency), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('maximum_proficiency') } }
      # The proficiency level of the skill
      field :minimum_proficiency, T.nilable(::StackOne::Shared::MinimumProficiency), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('minimum_proficiency') } }
      # The name associated with this skill
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('name') } }
      # Provider's unique identifier
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('remote_id') } }


      sig { params(active: T.nilable(T::Boolean), id: T.nilable(::String), language: T.nilable(::StackOne::Shared::EntitySkillsLanguage), maximum_proficiency: T.nilable(::StackOne::Shared::MaximumProficiency), minimum_proficiency: T.nilable(::StackOne::Shared::MinimumProficiency), name: T.nilable(::String), remote_id: T.nilable(::String)).void }
      def initialize(active: nil, id: nil, language: nil, maximum_proficiency: nil, minimum_proficiency: nil, name: nil, remote_id: nil)
        @active = active
        @id = id
        @language = language
        @maximum_proficiency = maximum_proficiency
        @minimum_proficiency = minimum_proficiency
        @name = name
        @remote_id = remote_id
      end
    end
  end
end
