# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class EventMetaItem
        extend T::Sig
        include Crystalline::MetadataFields

        # The authentication methods supported by this event
        field :authentication, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::AuthenticationMetaItem)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('authentication') } }
        # The event description
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('description') } }
        # The event ID
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }
        # The event label
        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('label') } }
        # The release stage of the event (e.g., ga, beta, preview)
        field :release_stage, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('release_stage') } }
        # Whether the event requires manual setup
        field :requires_manual_setup, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('requires_manual_setup') } }
        # The tags associated with this event
        field :tags, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('tags') } }

        sig { params(authentication: T.nilable(T::Array[Models::Shared::AuthenticationMetaItem]), description: T.nilable(::String), id: T.nilable(::String), label: T.nilable(::String), release_stage: T.nilable(::String), requires_manual_setup: T.nilable(T::Boolean), tags: T.nilable(T::Array[::String])).void }
        def initialize(authentication: nil, description: nil, id: nil, label: nil, release_stage: nil, requires_manual_setup: nil, tags: nil)
          @authentication = authentication
          @description = description
          @id = id
          @label = label
          @release_stage = release_stage
          @requires_manual_setup = requires_manual_setup
          @tags = tags
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @authentication == other.authentication
          return false unless @description == other.description
          return false unless @id == other.id
          return false unless @label == other.label
          return false unless @release_stage == other.release_stage
          return false unless @requires_manual_setup == other.requires_manual_setup
          return false unless @tags == other.tags
          true
        end
      end
    end
  end
end
