# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # Authentication guides for this authentication type
      class Guides
        extend T::Sig
        include Crystalline::MetadataFields

        # Configuration guide
        field :config, Crystalline::Nilable.new(Models::Shared::Config), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('config') } }
        # Account linking guide
        field :setup, Crystalline::Nilable.new(Models::Shared::Setup), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('setup') } }

        sig { params(config: T.nilable(Models::Shared::Config), setup: T.nilable(Models::Shared::Setup)).void }
        def initialize(config: nil, setup: nil)
          @config = config
          @setup = setup
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @config == other.config
          return false unless @setup == other.setup
          true
        end
      end
    end
  end
end
