# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class GuideStepMeta
        extend T::Sig
        include Crystalline::MetadataFields

        # The content of the step, includes markdown formatting
        field :content, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('content'), required: true } }
        # The title of the step
        field :title, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('title'), required: true } }
        # List items for the step
        field :list, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('list') } }

        sig { params(content: ::String, title: ::String, list: T.nilable(T::Array[::String])).void }
        def initialize(content:, title:, list: nil)
          @content = content
          @title = title
          @list = list
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content == other.content
          return false unless @title == other.title
          return false unless @list == other.list
          true
        end
      end
    end
  end
end
