# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # HRISLocationSchemasValue - The type of the location.
      class HRISLocationSchemasValue
        include ::Crystalline::Enum
        enums do
          HOME = new('home')
          WORK = new('work')
          UNMAPPED_VALUE = new('unmapped_value')
        end
        open!
      end
    end
  end
end
