# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class HrisUpdateEmploymentRequestDtoWorkTime
        extend T::Sig
        include Crystalline::MetadataFields

        # The work time duration in ISO 8601 duration format
        field :duration, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('duration') } }
        # The duration unit of the work time
        field :duration_unit, T.nilable(Models::Shared::HrisUpdateEmploymentRequestDtoDurationUnit), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('duration_unit') } }


        sig { params(duration: T.nilable(::String), duration_unit: T.nilable(Models::Shared::HrisUpdateEmploymentRequestDtoDurationUnit)).void }
        def initialize(duration: nil, duration_unit: nil)
          @duration = duration
          @duration_unit = duration_unit
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @duration == other.duration
          return false unless @duration_unit == other.duration_unit
          true
        end
      end
    end
  end
end
