# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class HRISTeamValue
        include ::Crystalline::Enum
        enums do
          TEAM = new('team')
          UNMAPPED_VALUE = new('unmapped_value')
        end
        open!
      end
    end
  end
end
