# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # HrisJobValue - The status of the job.
      class HrisJobValue < T::Enum


        enums do
          DRAFT = new('draft')
          PENDING = new('pending')
          ARCHIVED = new('archived')
          CLOSED = new('closed')
          OPEN = new('open')
          DELETED = new('deleted')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
