# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # HRISBankDetailsValue - The type of bank account
      class HRISBankDetailsValue < T::Enum


        enums do
          SAVINGS = new('savings')
          CHECKING = new('checking')
          CURRENT = new('current')
          BUSINESS = new('business')
          PERSONAL = new('personal')
          OTHER = new('other')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
