# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class HRISBenefit
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of the benefit
        field :benefit_type, Crystalline::Nilable.new(Models::Shared::HRISBenefitBenefitType), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('benefit_type') } }
        # The date and time the benefit was created
        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # The description of the benefit
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('description') } }
        # Unique identifier
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }
        # The name of the benefit
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('name') } }
        # The provider of the benefit
        field :provider, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('provider') } }
        # Provider's unique identifier
        field :remote_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('remote_id') } }
        # The date and time the benefit was last updated
        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }

        sig { params(benefit_type: T.nilable(Models::Shared::HRISBenefitBenefitType), created_at: T.nilable(::DateTime), description: T.nilable(::String), id: T.nilable(::String), name: T.nilable(::String), provider: T.nilable(::String), remote_id: T.nilable(::String), updated_at: T.nilable(::DateTime)).void }
        def initialize(benefit_type: nil, created_at: nil, description: nil, id: nil, name: nil, provider: nil, remote_id: nil, updated_at: nil)
          @benefit_type = benefit_type
          @created_at = created_at
          @description = description
          @id = id
          @name = name
          @provider = provider
          @remote_id = remote_id
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @benefit_type == other.benefit_type
          return false unless @created_at == other.created_at
          return false unless @description == other.description
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @provider == other.provider
          return false unless @remote_id == other.remote_id
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
