# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class HRISDepartmentValue
        include ::Crystalline::Enum
        enums do
          DEPARTMENT = new('department')
          COMPANY = new('company')
          DIVISION = new('division')
          GROUP = new('group')
          PROJECT = new('project')
          TEAM = new('team')
          UNMAPPED_VALUE = new('unmapped_value')
        end
        open!
      end
    end
  end
end
