# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # IamCredentialsValue - How the connection authenticates.
      class IamCredentialsValue
        include ::Crystalline::Enum
        enums do
          OAUTH = new('oauth')
          API_KEY = new('api_key')
          SERVICE_USER = new('service_user')
          UNMAPPED_VALUE = new('unmapped_value')
        end
        open!
      end
    end
  end
end
