# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class InterviewsPaginated
        extend T::Sig
        include Crystalline::MetadataFields


        field :data, Crystalline::Array.new(Models::Shared::Interview), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('data'), required: true } }

        field :next_, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('next') } }
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :next_page, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('next_page') } }

        field :raw, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::RawResponse)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('raw') } }

        sig { params(data: T::Array[Models::Shared::Interview], next_: T.nilable(::String), next_page: T.nilable(::String), raw: T.nilable(T::Array[Models::Shared::RawResponse])).void }
        def initialize(data:, next_: nil, next_page: nil, raw: nil)
          @data = data
          @next_ = next_
          @next_page = next_page
          @raw = raw
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          return false unless @next_ == other.next_
          return false unless @next_page == other.next_page
          return false unless @raw == other.raw
          true
        end
      end
    end
  end
end
