# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # IntervalType - The time interval to bucket results by
      class IntervalType
        include ::Crystalline::Enum
        enums do
          MINUTE = new('minute')
          HOUR = new('hour')
          DAY = new('day')
          WEEK = new('week')
          MONTH = new('month')
        end
        open!
      end
    end
  end
end
