# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # The employee job description
      # 
      # @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
      class JobDescription
        extend T::Sig
        include Crystalline::MetadataFields


        field :text, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('text') } }


        sig { params(text: T.nilable(::String)).void }
        def initialize(text: nil)
          @text = text
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @text == other.text
          true
        end
      end
    end
  end
end
