# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # The labor type associated with this time entry
    class LaborType < ::StackOne::Utils::FieldAugmented
      extend T::Sig


      field :code, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('code') } }


      sig { params(code: T.nilable(::String)).void }
      def initialize(code: nil)
        @code = code
      end
    end
  end
end
