# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class LinkedAccount
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id'), required: true } }

        field :origin_owner_id, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('origin_owner_id'), required: true } }

        field :origin_owner_name, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('origin_owner_name'), required: true } }

        field :provider, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('provider'), required: true } }

        field :status, Models::Shared::LinkedAccountStatus, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('status'), required: true, 'decoder': ::StackOne::Utils.open_enum_from_string(Models::Shared::LinkedAccountStatus, false) } }
        # The categories this provider belongs to (e.g., hris, ats, crm)
        field :categories, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('categories') } }

        field :created_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('created_at'), 'decoder': ::StackOne::Utils.datetime_from_iso_format(true) } }

        field :credentials, Crystalline::Nilable.new(Models::Shared::Credentials), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('credentials') } }

        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('label') } }

        field :origin_username, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('origin_username') } }

        field :provider_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('provider_name') } }

        field :setup_information, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('setup_information') } }

        field :shared, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('shared') } }

        field :status_reasons, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::StatusReason)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('status_reasons') } }
        # The account type
        field :type, Crystalline::Nilable.new(Models::Shared::LinkedAccountType), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('type'), 'decoder': ::StackOne::Utils.open_enum_from_string(Models::Shared::LinkedAccountType, true) } }

        field :updated_at, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('updated_at'), 'decoder': ::StackOne::Utils.datetime_from_iso_format(true) } }

        sig { params(id: ::String, origin_owner_id: ::String, origin_owner_name: ::String, provider: ::String, status: Models::Shared::LinkedAccountStatus, categories: T.nilable(T::Array[::String]), created_at: T.nilable(::DateTime), credentials: T.nilable(Models::Shared::Credentials), label: T.nilable(::String), origin_username: T.nilable(::String), provider_name: T.nilable(::String), setup_information: T.nilable(T::Hash[Symbol, ::Object]), shared: T.nilable(T::Boolean), status_reasons: T.nilable(T::Array[Models::Shared::StatusReason]), type: T.nilable(Models::Shared::LinkedAccountType), updated_at: T.nilable(::DateTime)).void }
        def initialize(id:, origin_owner_id:, origin_owner_name:, provider:, status:, categories: nil, created_at: nil, credentials: nil, label: nil, origin_username: nil, provider_name: nil, setup_information: nil, shared: nil, status_reasons: nil, type: nil, updated_at: nil)
          @id = id
          @origin_owner_id = origin_owner_id
          @origin_owner_name = origin_owner_name
          @provider = provider
          @status = status
          @categories = categories
          @created_at = created_at
          @credentials = credentials
          @label = label
          @origin_username = origin_username
          @provider_name = provider_name
          @setup_information = setup_information
          @shared = shared
          @status_reasons = status_reasons
          @type = type
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @origin_owner_id == other.origin_owner_id
          return false unless @origin_owner_name == other.origin_owner_name
          return false unless @provider == other.provider
          return false unless @status == other.status
          return false unless @categories == other.categories
          return false unless @created_at == other.created_at
          return false unless @credentials == other.credentials
          return false unless @label == other.label
          return false unless @origin_username == other.origin_username
          return false unless @provider_name == other.provider_name
          return false unless @setup_information == other.setup_information
          return false unless @shared == other.shared
          return false unless @status_reasons == other.status_reasons
          return false unless @type == other.type
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
