# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class LmsBatchUpsertContentRequestDto
        extend T::Sig
        include Crystalline::MetadataFields

        # The batch of items to upsert
        field :items, Crystalline::Array.new(Models::Shared::LmsUpsertContentRequestDto), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('items'), required: true } }

        sig { params(items: T::Array[Models::Shared::LmsUpsertContentRequestDto]).void }
        def initialize(items:)
          @items = items
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @items == other.items
          true
        end
      end
    end
  end
end
