# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class LmsCreateContentRequestDtoValue < T::Enum
      enums do
        AUTOMATIC = new('automatic')
        BROWSER = new('browser')
      end
    end
  end
end
