# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class LmsUpsertContentRequestDtoValue < T::Enum
      enums do
        VIDEO = new('video')
        QUIZ = new('quiz')
        DOCUMENT = new('document')
        AUDIO = new('audio')
        ARTICLE = new('article')
      end
    end
  end
end
