# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # NoteValue - The visibility of the notes.
      class NoteValue < T::Enum


        enums do
          PRIVATE = new('private')
          PUBLIC = new('public')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
