# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # PatchAccountExternalDtoType - The account type
      class PatchAccountExternalDtoType < T::Enum
        enums do
          PRODUCTION = new('production')
          TEST = new('test')
        end
      end
    end
  end
end
