# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class ResultLink
        extend T::Sig
        include Crystalline::MetadataFields

        # The label of the result link.
        field :label, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('label') } }
        # The URL of the result link.
        field :url, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('url') } }

        sig { params(label: T.nilable(::String), url: T.nilable(::String)).void }
        def initialize(label: nil, url: nil)
          @label = label
          @url = url
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @label == other.label
          return false unless @url == other.url
          true
        end
      end
    end
  end
end
