# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # ScreeningResultStatus - Result status
      class ScreeningResultStatus < T::Enum
        enums do
          PENDING = new('pending')
          IN_PROGRESS = new('in_progress')
          COMPLETED = new('completed')
          FAILED = new('failed')
          CANCELLED = new('cancelled')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
