# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    

      class StepLogsPaginated
        extend T::Sig
        include Crystalline::MetadataFields


        field :data, T::Array[Models::Shared::StepLogsApiModel], { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('data') } }

        field :next_, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('next') } }


        sig { params(data: T::Array[Models::Shared::StepLogsApiModel], next_: T.nilable(::String)).void }
        def initialize(data: nil, next_: nil)
          @data = data
          @next_ = next_
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @data == other.data
          return false unless @next_ == other.next_
          true
        end
      end
    end
  end
end
