# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
      # The support information for this authentication method, including configuration and account linking guides
      class Support
        extend T::Sig
        include Crystalline::MetadataFields

        # Support description
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('description') } }
        # Authentication guides for this authentication type
        field :guides, Crystalline::Nilable.new(Models::Shared::Guides), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('guides') } }
        # Link to support documentation
        field :link, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('link') } }

        sig { params(description: T.nilable(::String), guides: T.nilable(Models::Shared::Guides), link: T.nilable(::String)).void }
        def initialize(description: nil, guides: nil, link: nil)
          @description = description
          @guides = guides
          @link = link
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @description == other.description
          return false unless @guides == other.guides
          return false unless @link == other.link
          true
        end
      end
    end
  end
end
