# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared
    
      # TicketingTicketResultSchemasValue - The type of this status
      class TicketingTicketResultSchemasValue < T::Enum
        enums do
          TO_DO = new('to-do')
          IN_PROGRESS = new('in-progress')
          CLOSED = new('closed')
          UNMAPPED_VALUE = new('unmapped_value')
        end
      end
    end
  end
end
