# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class TimeOffBalancesValue < T::Enum
      enums do
        MINUTES = new('minutes')
        HOURS = new('hours')
        DAYS = new('days')
        WEEKS = new('weeks')
        MONTHS = new('months')
        YEARS = new('years')
      end
    end
  end
end
