# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class UpsertConnectorProfilePinnedVersion
        extend T::Sig
        include Crystalline::MetadataFields

        # The version to pin for the connector profile
        field :pinned_version, ::String, { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('pinned_version'), required: true } }
        # The owner of the pinned version
        field :owner, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('owner') } }

        sig { params(pinned_version: ::String, owner: T.nilable(::String)).void }
        def initialize(pinned_version:, owner: nil)
          @pinned_version = pinned_version
          @owner = owner
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @pinned_version == other.pinned_version
          return false unless @owner == other.owner
          true
        end
      end
    end
  end
end
