# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Models
    module Shared

      class User
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }

        field :permissions, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('permissions') } }

        sig { params(id: T.nilable(::String), permissions: T.nilable(T::Array[::String])).void }
        def initialize(id: nil, permissions: nil)
          @id = id
          @permissions = permissions
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @permissions == other.permissions
          true
        end
      end
    end
  end
end
